apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: example-pipelinerun-
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/geriom/tekton-signed-resourcs
      - name: revision
        value: main
      - name: pathInRepo
        value: signed-pipeline-cosign.yaml
